server:
  port: 8701

spring:
  application:
    name: gateway-service-zuul
    
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: eurekacus
    api-b:
      path: /api-b/**
      serviceId: eurekac   
    abc:
      path: /wai/**
      url: http://www.baidu.com/  
    my:
      path: /my/*
      url: http://www.butel.com/service/exchange    
         
eureka:
  client:
     registerWithEureka: true
     fetchRegistry: true
     serviceUrl:
      defaultZone: http://localhost:8010/eureka/
      
   
 